### ISSUE TITLE
[API] 회원가입 기능

### ISSUE THREAD

**Issue by JeongminSeon** [FE-J1/taskify#29]
## 🚀 Description

이 API는 클라이언트에서 이메일 , 닉네임, 비밀번호 정보를 전달하며, 서버는 해당 정보를 바탕으로 회원을 생성합니다.

- **Endpoint**: `/team/{teamId}/users`
- **Method**: `POST`
- **Purpose**: 회원가입 페이지에서 새로운 사용자를 등록합니다.

## ✅ TODO

- [x] API 호출 기능 구현 (Axios 사용 예정) 
- [x] teamId, 이메일, 닉네임, 비밀번호를 포함한 파라미터 전달
- [x] 중복된 이메일이 있는지 확인 (409 Conflict 처리)
- [x] JWT 토큰 인증 로직 포함 여부 확인 (회원가입 후 인증 처리 필요 시)

### API Info

- **API Reference**: [Swagger API 문서 링크](https://sp-taskify-api.vercel.app/docs/#/Users/Create)  
- **Endpoint**: `/team/{teamId}/users`
- **Method**: `POST`
- **Headers**: 
  - `Content-Type: application/json`
  - `Authorization: Bearer <token>` (필요 시)

### Response Example

- 409 ConflictException 
```json
{
  "message": "이미 사용 중인 이메일입니다."
}
```

### Additional Context
- 추가적인 정보나 스크린샷이 필요하면 첨부해주세요.
- 없지롱~
