### ISSUE TITLE
[API] 로그인 API

### ISSUE THREAD

**Issue by JeongminSeon** [FE-J1/taskify#30]
## 🚀 Description

로그인 API는 사용자의 이메일과 비밀번호를 사용하여 인증을 수행하고, 성공 시 `accessToken`을 반환하여 추후 인증된 요청을 보낼 수 있도록 합니다.

- **Endpoint**: `/teamId/auth/login`
- **Method**: `POST`
- **Purpose**: 사용자의 로그인 요청을 처리하고, 인증된 사용자의 정보를 반환합니다.

## ✅ TODO

- [x] API 호출 기능 구현 (`POST /{teamId}/auth/login`)
- [x] 이메일과 비밀번호를 전송하여 로그인 처리
- [x] `accessToken`을 받아서 저장 (쿠키 또는 로컬 스토리지)
- [x] 에러 핸들링 (예: 이메일 형식 오류, 존재하지 않는 사용자 등)

### API Info

- **API Reference**: [Swagger API 문서 링크](https://sp-taskify-api.vercel.app/docs/#/Auth/Login)  
- **Endpoint**: `/teamId/auth/login`
- **Method**: `POST`
- **Headers**: 
  - `Content-Type: application/json`
  - `Authorization: Bearer <token>` (필요 시)

### Response Example

```json
{
  "email": "string",
  "password": "string"
}
```

### Response Example

```json
{
  "user": {
    "id": 0,
    "email": "string",
    "nickname": "string",
    "profileImageUrl": "string",
    "createdAt": "2024-10-22T14:14:12.029Z",
    "updatedAt": "2024-10-22T14:14:12.029Z"
  },
  "accessToken": "string"
}
```

- **400 BadRequest** : 이메일 형식 오류 시
 ```json
{
  "message": "이메일 형식으로 작성해주세요."
}
```

- **404 NotFoundException** : 존재하지 않는 사용자일 경우
```json
{
  "message": "존재하지 않는 유저입니다."
}
```

### Additional Context
- 추가적인 정보나 스크린샷이 필요하면 첨부해주세요.
