### ISSUE TITLE
Feat : 대시보드 수정 구현

### ISSUE THREAD

**Issue by 99minji** [FE-J1/taskify#32]
# 🚀 Description
## 구현된 기능
1. 대시보드 수정 페이지 /dashboard/{dashboardId}/edit
2. Context API 사용 -> zustand 로 추후 변경하겠습니다.
3. dashobards/[dashboradid]/edit.tsx 에서 getServerSideProps 사용하여 멤버 목록 'getMembers ' 함수 호출 했습니다.
ㄴ 서버사이드 렌더링 작업이 미숙하여 추후 수정해야 할 것 같습니다 😭
4. edit 페이지에서 '변경' 버튼 시 입력한 '이름'.'컬러'로 바로 반영되게 구현했습니다.

# ✅ TODO 해야 할 

- [x] '관리' 버튼을 누르면 /dashboard/{boardid}/edit로 이동합니다
- [x] 대시보드 이름이나 색을 바꾸고 '변경' 버튼을 누르면 대시보드가 수정됩니다.
- [x] '돌아가기' 버튼을 누르면 /boardid로 이동합니다.
- [x] 대시보드 각 구성원 오른쪽에 있는 '삭제' 버튼을 누르면 구성원이 삭제가 됩니다
- [x] 구성원 리스트는 페이지네이션으로 구현합니다.
- [x] 초대 내역 리스트는 페이지네이션으로 구현합니다.
- [ ] '초대하기' 버튼을 누르면 초대하기 모달창이 나타납니다.
- [x] 초대 내역 각 오른쪽의 '취소'버튼을 누르면 해당 초대는 취소가 됩니다.

## 관련 파일
1. 파일 구조 변경

[변경 전]
/pages
  └── /dashboard
      ├── [dashboardid].tsx
      └── index.tsx

[변경 후]
/pages
  └── /dashboard
      ├── [dashboardid]
      │   ├── edit.tsx     // '/dashboard/[id]/edit' URL을 처리하는 파일
      │   └── index.tsx
      └── index.tsx  // 예지님 테스트 페이지
