### ISSUE TITLE
Feat: createColumn 새로운 컬럼 생성 구현 완료

### ISSUE THREAD

**Issue by yyezzzy** [FE-J1/taskify#35]
## 🚀 Description

- **Endpoint**: /api/columns
- **Method**: GET, POST
- **Purpose**: 대시보드의 컬럼 목록을 조회하고 새로운 컬럼을 추가합니다.

## ✅ TODO
- [x] 컬럼 목록 조회 API 호출 기능 구현
- [x] 새로운 컬럼 추가 API 호출 기능 구현
- [x] 컬럼 추가를 위한 모달 구현
- [ ] 컬럼 삭제 기능 구현
- [ ] 컬럼 순서 변경 기능 구현
- [ ] 에러 처리 개선 및 사용자 피드백 강화
### API Info

- **API Reference**: [Swagger API 문서 링크](https://sp-taskify-api.vercel.app/docs/#/Columns/Create)

### Response Example
컬럼 조회 응답
```
{
  "data": [
    {
      "id": 1,
      "title": "To Do",
      "teamId": "9-1",
      "dashboardId": 1
    },
    {
      "id": 2,
      "title": "In Progress",
      "teamId": "9-1",
      "dashboardId": 1
    }
  ]
}
```
컬럼 생성 응답
```
{
  "id": 3,
  "title": "새로운 컬럼",
  "teamId": "9-1",
  "dashboardId": 1
}
```

### 🌟 추가사항
<img width="476" alt="image" src="https://github.com/user-attachments/assets/e3c3a939-31b6-4520-a257-b36d0602d8ca">
