### ISSUE TITLE
Feat : 새로운 대시보드 생성 기능

### ISSUE THREAD

**Issue by JeongminSeon** [FE-J1/taskify#51]
### Sub-features or Key Behaviors:

1. [x] 새로운 생성 대시보드를 클릭하면 모달 생성 창이 뜬다.
2. [x] 대시보드 이름 입력하고 색깔을 선택해야만, '생성' 버튼이 활성화 됨
3. [x] 대시보드 생성 버튼을 누르면 대시보드가 생성되고 dashboard/{dashboardid}로 이동

## ✅ TODO

- [x] UI 디자인
- [x] 입력 유효성 검사 처리
- [x] API 연동 

## 🗂 Related Issues

- #123 (관련 이슈)

## 📚 References

- [디자인 시스템 링크](#)
- [관련 API 문서](#)
- [참고할 만한 구현 사례](#)
